name: ai-tour-26

networks:
  zava-network:
    driver: bridge

services:
  db:
    build:
      context: .
      dockerfile_inline: |
        FROM pgvector/pgvector:pg17
        COPY scripts/init-db.sh /docker-entrypoint-initdb.d/init-db.sh
        RUN chmod +x /docker-entrypoint-initdb.d/init-db.sh
    container_name: ai-tour-26
    ports:
      - "15432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P@ssw0rd!
    volumes:
      - zava_postgresql_data:/var/lib/postgresql/data
      - ./data:/docker-entrypoint-initdb.d/backups:ro
    networks:
      - zava-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 30s
      timeout: 15s
      retries: 20
      start_period: 180s

volumes:
  zava_postgresql_data:
    driver: local
